#!/usr/bin/php
<?php

//include application commands
include_once('app/Application.php');

executeCommand();

/**
 * execute easylib using flags to determine what to do
 *
 * for example
 * "easylib scan" will scan
 * "easylib scan help" will scan and the print the help
 */
function executeCommand(){
    //get arguments
    $argv = $_SERVER['argv'];
    $totalArgv = count($argv);

    //if any arguments execute them
    if( $totalArgv > 1 ){
        //first arg is function
        $func = $argv[1];
        //parameters
        $param = array();
        //loop all and get the parameters
        for( $x = 2; $x < $totalArgv; $x++ ) {
            //add params
            array_push($param, trim($argv[$x]));
        }
        //execute func
        $func($param);
    }else{
        help();
    }
}
?>